### ISSUE TITLE
Gerbers update?

### ISSUE THREAD

**Issue by JaimieVandenbergh** [PR77/68000_Relocator_FLASH_Kickstart#6]
Seems the gerbers here don't work with the current PCB sites - jlc and osh get the network and holes but fail to find the actual PCB or screenprint details. KiCAD6 gets the same. Would it be possible to update/refresh the gerbers zip?

**Comment by PR77** [comment]
Seems the ZIP file never had the complete set of gerber files - thanks for highlighting this. It has now been corrected.
